import Head from "next/head";
import Navbar from "./navbar";

export default function Layout({ children, title = 'Velizar | Web Developer' }) {
    return (
        <div>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by V.Ganchev" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            {children}
        </div>
    )
}
